return {
  ["ADR-001"] = { title = "Adopt open protocols for federation and provisioning", href = "architecture/decisions.html#ADR-001", type = "architecture-decision", status = "accepted" },
  ["ADR-002"] = { title = "Centralize authorization in a policy engine", href = "architecture/decisions.html#ADR-002", type = "architecture-decision", status = "accepted" },
  ["ADR-003"] = { title = "Separate the audit trail from transactional processing", href = "architecture/decisions.html#ADR-003", type = "architecture-decision", status = "accepted" },
  ["COMP-001"] = { title = "Authentication service", href = "architecture/components.html#COMP-001", type = "component", status = "implemented" },
  ["COMP-002"] = { title = "Policy engine", href = "architecture/components.html#COMP-002", type = "component", status = "implemented" },
  ["COMP-003"] = { title = "Lifecycle orchestrator", href = "architecture/components.html#COMP-003", type = "component", status = "implemented" },
  ["COMP-004"] = { title = "Audit vault", href = "architecture/components.html#COMP-004", type = "component", status = "implemented" },
  ["COMP-005"] = { title = "Recovery service", href = "architecture/components.html#COMP-005", type = "component", status = "implemented" },
  ["COMP-006"] = { title = "Identity portal", href = "architecture/components.html#COMP-006", type = "component", status = "implemented" },
  ["EVD-001"] = { title = "Authentication report 2026-08-25", href = "verification/evidence.html#EVD-001", type = "evidence", status = "verified" },
  ["EVD-002"] = { title = "Administrative MFA report", href = "verification/evidence.html#EVD-002", type = "evidence", status = "verified" },
  ["EVD-003"] = { title = "Session-revocation report", href = "verification/evidence.html#EVD-003", type = "evidence", status = "verified" },
  ["EVD-004"] = { title = "Attribute-policy report", href = "verification/evidence.html#EVD-004", type = "evidence", status = "verified" },
  ["EVD-005"] = { title = "Default-denial report", href = "verification/evidence.html#EVD-005", type = "evidence", status = "verified" },
  ["EVD-006"] = { title = "Authorization load report", href = "verification/evidence.html#EVD-006", type = "evidence", status = "verified" },
  ["EVD-007"] = { title = "Onboarding-provisioning report", href = "verification/evidence.html#EVD-007", type = "evidence", status = "verified" },
  ["EVD-008"] = { title = "Offboarding-suspension report", href = "verification/evidence.html#EVD-008", type = "evidence", status = "verified" },
  ["EVD-009"] = { title = "Review-campaign report", href = "verification/evidence.html#EVD-009", type = "evidence", status = "verified" },
  ["EVD-010"] = { title = "Authorization-event report", href = "verification/evidence.html#EVD-010", type = "evidence", status = "verified" },
  ["EVD-011"] = { title = "Query and retention report", href = "verification/evidence.html#EVD-011", type = "evidence", status = "verified" },
  ["EVD-012"] = { title = "Strengthened-recovery report", href = "verification/evidence.html#EVD-012", type = "evidence", status = "verified" },
  ["EVD-013"] = { title = "Portal-accessibility report", href = "verification/evidence.html#EVD-013", type = "evidence", status = "verified" },
  ["EVD-014"] = { title = "Authentication-availability report", href = "verification/evidence.html#EVD-014", type = "evidence", status = "verified" },
  ["EVD-015"] = { title = "Data-minimization report", href = "verification/evidence.html#EVD-015", type = "evidence", status = "verified" },
  ["EVD-016"] = { title = "Credential-encryption report", href = "verification/evidence.html#EVD-016", type = "evidence", status = "verified" },
  ["EVD-017"] = { title = "OIDC interoperability report", href = "verification/evidence.html#EVD-017", type = "evidence", status = "verified" },
  ["FUN-001"] = { title = "Validate corporate credentials", href = "requirements/functional.html#FUN-001", type = "functional-requirement", status = "approved" },
  ["FUN-002"] = { title = "Require MFA for privileged access", href = "requirements/functional.html#FUN-002", type = "functional-requirement", status = "approved" },
  ["FUN-003"] = { title = "Revoke sessions after a risk change", href = "requirements/functional.html#FUN-003", type = "functional-requirement", status = "approved" },
  ["FUN-004"] = { title = "Evaluate attribute-based policies", href = "requirements/functional.html#FUN-004", type = "functional-requirement", status = "approved" },
  ["FUN-005"] = { title = "Enforce least privilege by default", href = "requirements/functional.html#FUN-005", type = "functional-requirement", status = "approved" },
  ["FUN-006"] = { title = "Record temporary delegation", href = "requirements/functional.html#FUN-006", type = "functional-requirement", status = "approved" },
  ["FUN-007"] = { title = "Provision an account from an onboarding event", href = "requirements/functional.html#FUN-007", type = "functional-requirement", status = "approved" },
  ["FUN-008"] = { title = "Suspend an account on offboarding", href = "requirements/functional.html#FUN-008", type = "functional-requirement", status = "approved" },
  ["FUN-009"] = { title = "Request periodic access review", href = "requirements/functional.html#FUN-009", type = "functional-requirement", status = "approved" },
  ["FUN-010"] = { title = "Record the authorization decision", href = "requirements/functional.html#FUN-010", type = "functional-requirement", status = "approved" },
  ["FUN-011"] = { title = "Query the audit trail by account", href = "requirements/functional.html#FUN-011", type = "functional-requirement", status = "approved" },
  ["FUN-012"] = { title = "Recover an account with strengthened verification", href = "requirements/functional.html#FUN-012", type = "functional-requirement", status = "approved" },
  ["FUN-013"] = { title = "Delegate recovery to supervised support", href = "requirements/functional.html#FUN-013", type = "functional-requirement", status = "in-review" },
  ["FUN-014"] = { title = "Provision groups through SCIM", href = "requirements/functional.html#FUN-014", type = "functional-requirement", status = "draft" },
  ["FUN-015"] = { title = "Allow a shared team password", href = "requirements/functional.html#FUN-015", type = "functional-requirement", status = "disapproved" },
  ["IF-001"] = { title = "OpenID Connect API", href = "architecture/components.html#IF-001", type = "interface", status = "implemented" },
  ["IF-002"] = { title = "SCIM provisioning API", href = "architecture/components.html#IF-002", type = "interface", status = "implemented" },
  ["IF-003"] = { title = "Audit event stream", href = "architecture/components.html#IF-003", type = "interface", status = "implemented" },
  ["NFR-001"] = { title = "Protect credentials in transit and at rest", href = "requirements/non-functional.html#NFR-001", type = "non-functional-requirement", status = "approved" },
  ["NFR-002"] = { title = "Keep authentication available", href = "requirements/non-functional.html#NFR-002", type = "non-functional-requirement", status = "approved" },
  ["NFR-003"] = { title = "Minimize personal data in events", href = "requirements/non-functional.html#NFR-003", type = "non-functional-requirement", status = "approved" },
  ["NFR-004"] = { title = "Respond to access decisions within 200 ms", href = "requirements/non-functional.html#NFR-004", type = "non-functional-requirement", status = "approved" },
  ["NFR-005"] = { title = "Preserve audit integrity", href = "requirements/non-functional.html#NFR-005", type = "non-functional-requirement", status = "approved" },
  ["NFR-006"] = { title = "Provide accessible authentication", href = "requirements/non-functional.html#NFR-006", type = "non-functional-requirement", status = "approved" },
  ["NFR-007"] = { title = "Retain evidence for the regulatory period", href = "requirements/non-functional.html#NFR-007", type = "non-functional-requirement", status = "approved" },
  ["NFR-008"] = { title = "Restore the recovery flow within four hours", href = "requirements/non-functional.html#NFR-008", type = "non-functional-requirement", status = "approved" },
  ["NFR-009"] = { title = "Expose operational identity metrics", href = "requirements/non-functional.html#NFR-009", type = "non-functional-requirement", status = "in-review" },
  ["NFR-010"] = { title = "Measure energy consumption per authentication", href = "requirements/non-functional.html#NFR-010", type = "non-functional-requirement", status = "draft" },
  ["RISK-001"] = { title = "Account takeover through phishing", href = "risks/security.html#RISK-001", type = "risk", status = "in-review" },
  ["RISK-002"] = { title = "Privilege escalation through permissive policy", href = "risks/security.html#RISK-002", type = "risk", status = "approved" },
  ["RISK-003"] = { title = "Personal-data leakage in logs", href = "risks/security.html#RISK-003", type = "risk", status = "approved" },
  ["RISK-004"] = { title = "Unavailability during account recovery", href = "risks/security.html#RISK-004", type = "risk", status = "draft" },
  ["STK-001"] = { title = "Security leadership needs to reduce account takeovers", href = "context/stakeholders.html#STK-001", type = "stakeholder-need", status = "approved" },
  ["STK-002"] = { title = "Data protection needs control over personal-data exposure", href = "context/stakeholders.html#STK-002", type = "stakeholder-need", status = "approved" },
  ["STK-003"] = { title = "Operations needs to recover access safely", href = "context/stakeholders.html#STK-003", type = "stakeholder-need", status = "approved" },
  ["STK-004"] = { title = "Product teams need to integrate applications quickly", href = "context/stakeholders.html#STK-004", type = "stakeholder-need", status = "approved" },
  ["STK-005"] = { title = "Audit needs traceability for access decisions", href = "context/stakeholders.html#STK-005", type = "stakeholder-need", status = "approved" },
  ["SYS-001"] = { title = "Authenticate identities before issuing a session", href = "requirements/system.html#SYS-001", type = "system-requirement", status = "approved" },
  ["SYS-002"] = { title = "Decide access through central policy", href = "requirements/system.html#SYS-002", type = "system-requirement", status = "approved" },
  ["SYS-003"] = { title = "Manage the account lifecycle", href = "requirements/system.html#SYS-003", type = "system-requirement", status = "approved" },
  ["SYS-004"] = { title = "Record immutable identity events", href = "requirements/system.html#SYS-004", type = "system-requirement", status = "approved" },
  ["SYS-005"] = { title = "Recover access with identity proofing", href = "requirements/system.html#SYS-005", type = "system-requirement", status = "approved" },
  ["SYS-006"] = { title = "Expose standardized identity integration", href = "requirements/system.html#SYS-006", type = "system-requirement", status = "approved" },
  ["SYS-007"] = { title = "Detect privilege anomalies", href = "requirements/system.html#SYS-007", type = "system-requirement", status = "in-review" },
  ["SYS-008"] = { title = "Offer a corporate mobile credential", href = "requirements/system.html#SYS-008", type = "system-requirement", status = "draft" },
  ["TC-001"] = { title = "Authentication with a valid credential", href = "verification/test-cases.html#TC-001", type = "test-case", status = "passed" },
  ["TC-002"] = { title = "Mandatory MFA for administrators", href = "verification/test-cases.html#TC-002", type = "test-case", status = "passed" },
  ["TC-003"] = { title = "Suspended-session revocation", href = "verification/test-cases.html#TC-003", type = "test-case", status = "passed" },
  ["TC-004"] = { title = "Attribute-based decision", href = "verification/test-cases.html#TC-004", type = "test-case", status = "passed" },
  ["TC-005"] = { title = "Denial without a permissive rule", href = "verification/test-cases.html#TC-005", type = "test-case", status = "passed" },
  ["TC-006"] = { title = "Access-decision latency", href = "verification/test-cases.html#TC-006", type = "test-case", status = "passed" },
  ["TC-007"] = { title = "Creation from an onboarding event", href = "verification/test-cases.html#TC-007", type = "test-case", status = "passed" },
  ["TC-008"] = { title = "Suspension on offboarding", href = "verification/test-cases.html#TC-008", type = "test-case", status = "passed" },
  ["TC-009"] = { title = "Access-review campaign", href = "verification/test-cases.html#TC-009", type = "test-case", status = "passed" },
  ["TC-010"] = { title = "Authorization-decision record", href = "verification/test-cases.html#TC-010", type = "test-case", status = "passed" },
  ["TC-011"] = { title = "Trail query and retention", href = "verification/test-cases.html#TC-011", type = "test-case", status = "passed" },
  ["TC-012"] = { title = "Strengthened recovery", href = "verification/test-cases.html#TC-012", type = "test-case", status = "passed" },
  ["TC-013"] = { title = "Authentication accessibility", href = "verification/test-cases.html#TC-013", type = "test-case", status = "passed" },
  ["TC-014"] = { title = "Authentication availability", href = "verification/test-cases.html#TC-014", type = "test-case", status = "passed" },
  ["TC-015"] = { title = "Personal-event minimization", href = "verification/test-cases.html#TC-015", type = "test-case", status = "passed" },
  ["TC-016"] = { title = "Credential and secret encryption", href = "verification/test-cases.html#TC-016", type = "test-case", status = "passed" },
  ["TC-017"] = { title = "OpenID Connect federation", href = "verification/test-cases.html#TC-017", type = "test-case", status = "passed" },
}
