return {
  ["ACTOR-ENGINEER"] = { title = "Requirements engineer", href = "architecture.html#ACTOR-ENGINEER", type = "actor", status = "approved" },
  ["ADR-001"] = { title = "Keep Python as the semantic authority", href = "architecture.html#ADR-001", type = "architecture-decision", status = "accepted" },
  ["ADR-002"] = { title = "Use Quarto as the executable documentation interface", href = "architecture.html#ADR-002", type = "architecture-decision", status = "accepted" },
  ["ADR-003"] = { title = "Model traceability as a typed property graph", href = "architecture.html#ADR-003", type = "architecture-decision", status = "accepted" },
  ["ADR-004"] = { title = "Drive static and interactive graphs from the same projection", href = "architecture.html#ADR-004", type = "architecture-decision", status = "accepted" },
  ["ADR-005"] = { title = "Keep English canonical and localization presentation-only", href = "architecture.html#ADR-005", type = "architecture-decision", status = "accepted" },
  ["ADR-006"] = { title = "Evaluate named queries in the core and materialize reusable views", href = "architecture.html#ADR-006", type = "architecture-decision", status = "accepted" },
  ["ADR-007"] = { title = "Treat the margin TOC control as persistent progressive enhancement", href = "architecture.html#ADR-007", type = "architecture-decision", status = "accepted" },
  ["ADR-008"] = { title = "Keep the first OSLC federation path read-only, bounded, and cache-provenanced", href = "interoperability.html#ADR-008", type = "architecture-decision", status = "accepted" },
  ["ADR-009"] = { title = "Require explicit URI-to-canonical-ID bindings for OSLC reconciliation", href = "interoperability.html#ADR-009", type = "architecture-decision", status = "accepted" },
  ["ADR-010"] = { title = "Keep the GitHub issues path read-only, bounded, and discovery-separated", href = "interoperability.html#ADR-010", type = "architecture-decision", status = "accepted" },
  ["ADR-011"] = { title = "Document Quarto-Needs itself through explicit viewpoints, indexed arc42-lite", href = "architecture.html#ADR-011", type = "architecture-decision", status = "accepted" },
  ["ADR-012"] = { title = "Model architectural roles as configurable types, not a fixed enumeration", href = "architecture.html#ADR-012", type = "architecture-decision", status = "accepted" },
  ["ADR-013"] = { title = "Represent architecture hierarchy and containment through a first-class part-of relation", href = "architecture.html#ADR-013", type = "architecture-decision", status = "accepted" },
  ["ADR-014"] = { title = "Reuse part-of instead of introducing a separate realized-by/realizes relation", href = "architecture.html#ADR-014", type = "architecture-decision", status = "accepted" },
  ["ADR-015"] = { title = "Derive C4/architecture projections from the canonical snapshot, never hand-author them", href = "architecture.html#ADR-015", type = "architecture-decision", status = "accepted" },
  ["ADR-016"] = { title = "Keep the architecture model renderer-independent", href = "architecture.html#ADR-016", type = "architecture-decision", status = "accepted" },
  ["ADR-017"] = { title = "Draw an explicit boundary between authored architecture declarations and generated projections", href = "architecture.html#ADR-017", type = "architecture-decision", status = "accepted" },
  ["ADR-018"] = { title = "Classify execution units (system, container) separately from logical components", href = "architecture.html#ADR-018", type = "architecture-decision", status = "accepted" },
  ["ADR-019"] = { title = "Provision a project-local managed runtime through an extension bootstrap", href = "architecture.html#ADR-019", type = "architecture-decision", status = "accepted" },
  ["ADR-020"] = { title = "Publish a narrow first supported release", href = "architecture.html#ADR-020", type = "architecture-decision", status = "accepted" },
  ["ADR-021"] = { title = "Classify the public surface into stability tiers from a single registry", href = "architecture.html#ADR-021", type = "architecture-decision", status = "accepted" },
  ["COMP-ANALYSIS"] = { title = "Semantic analysis core", href = "architecture.html#COMP-ANALYSIS", type = "component", status = "implemented" },
  ["COMP-BASELINE"] = { title = "Baseline and comparison subsystem", href = "architecture.html#COMP-BASELINE", type = "component", status = "implemented" },
  ["COMP-CLI"] = { title = "Command-line interface", href = "architecture.html#COMP-CLI", type = "component", status = "implemented" },
  ["COMP-EXTENSION"] = { title = "Quarto presentation extension", href = "architecture.html#COMP-EXTENSION", type = "component", status = "implemented" },
  ["COMP-GHISSUES"] = { title = "GitHub issues federation subsystem", href = "interoperability.html#COMP-GHISSUES", type = "component", status = "implemented" },
  ["COMP-GRAPH"] = { title = "Graph projection and exploration subsystem", href = "architecture.html#COMP-GRAPH", type = "component", status = "implemented" },
  ["COMP-I18N"] = { title = "Localization projection subsystem", href = "architecture.html#COMP-I18N", type = "component", status = "implemented" },
  ["COMP-OSLC"] = { title = "OSLC federation subsystem", href = "interoperability.html#COMP-OSLC", type = "component", status = "implemented" },
  ["COMP-PARSER"] = { title = "Declaration parser", href = "architecture.html#COMP-PARSER", type = "component", status = "implemented" },
  ["COMP-RULES"] = { title = "Governance rule engine", href = "architecture.html#COMP-RULES", type = "component", status = "implemented" },
  ["CONTAINER-PYTHON-PKG"] = { title = "Python package", href = "architecture.html#CONTAINER-PYTHON-PKG", type = "container", status = "approved" },
  ["CONTAINER-QUARTO-EXT"] = { title = "Quarto presentation extension", href = "architecture.html#CONTAINER-QUARTO-EXT", type = "container", status = "approved" },
  ["DEPLOY-LOCAL"] = { title = "Developer workstation", href = "architecture.html#DEPLOY-LOCAL", type = "deployment-node", status = "approved" },
  ["EVD-001"] = { title = "Analysis and export regression suite", href = "verification.html#EVD-001", type = "evidence", status = "verified" },
  ["EVD-002"] = { title = "Graph render and multilingual render smoke surfaces", href = "verification.html#EVD-002", type = "evidence", status = "verified" },
  ["EVD-003"] = { title = "Rule and quality-gate test suite", href = "verification.html#EVD-003", type = "evidence", status = "verified" },
  ["EVD-004"] = { title = "ADR governance machine evidence", href = "verification.html#EVD-004", type = "evidence", status = "verified" },
  ["EVD-005"] = { title = "Localization parity machine evidence", href = "verification.html#EVD-005", type = "evidence", status = "verified" },
  ["EVD-006"] = { title = "Public graph machine evidence", href = "verification.html#EVD-006", type = "evidence", status = "verified" },
  ["EVD-007"] = { title = "Parser regression suite", href = "verification.html#EVD-007", type = "evidence", status = "verified" },
  ["EVD-008"] = { title = "Relation catalog regression suite", href = "verification.html#EVD-008", type = "evidence", status = "verified" },
  ["EVD-009"] = { title = "Named-query graph-view machine evidence", href = "verification.html#EVD-009", type = "evidence", status = "verified" },
  ["EVD-010"] = { title = "Interactive graph asset integrity tests", href = "verification.html#EVD-010", type = "evidence", status = "verified" },
  ["EVD-011"] = { title = "Baseline and impact machine evidence", href = "verification.html#EVD-011", type = "evidence", status = "verified" },
  ["EVD-012"] = { title = "Canonical pre-render synchronization workflow", href = "verification.html#EVD-012", type = "evidence", status = "verified" },
  ["EVD-013"] = { title = "Determinism and fingerprint regression suite", href = "verification.html#EVD-013", type = "evidence", status = "verified" },
  ["EVD-014"] = { title = "Margin TOC usability machine evidence", href = "verification.html#EVD-014", type = "evidence", status = "verified" },
  ["EVD-015"] = { title = "OSLC federation machine evidence", href = "interoperability.html#EVD-015", type = "evidence", status = "verified" },
  ["EVD-016"] = { title = "OSLC reconciliation machine evidence", href = "interoperability.html#EVD-016", type = "evidence", status = "verified" },
  ["EVD-017"] = { title = "OSLC query machine evidence", href = "interoperability.html#EVD-017", type = "evidence", status = "verified" },
  ["EVD-018"] = { title = "OSLC member observation machine evidence", href = "interoperability.html#EVD-018", type = "evidence", status = "verified" },
  ["EVD-019"] = { title = "OSLC import-plan machine evidence", href = "interoperability.html#EVD-019", type = "evidence", status = "verified" },
  ["EVD-020"] = { title = "GitHub issue normalization machine evidence", href = "interoperability.html#EVD-020", type = "evidence", status = "verified" },
  ["EVD-021"] = { title = "GitHub conditional-request machine evidence", href = "interoperability.html#EVD-021", type = "evidence", status = "verified" },
  ["EVD-022"] = { title = "GitHub bounded pagination machine evidence", href = "interoperability.html#EVD-022", type = "evidence", status = "verified" },
  ["EVD-023"] = { title = "GitHub reconciliation machine evidence", href = "interoperability.html#EVD-023", type = "evidence", status = "verified" },
  ["EVD-024"] = { title = "GitHub rate-limit machine evidence", href = "interoperability.html#EVD-024", type = "evidence", status = "verified" },
  ["EVD-025"] = { title = "Extension-first clean render machine evidence", href = "verification.html#EVD-025", type = "evidence", status = "verified" },
  ["EVD-026"] = { title = "Offline second render machine evidence", href = "verification.html#EVD-026", type = "evidence", status = "verified" },
  ["EVD-027"] = { title = "Version skew isolation machine evidence", href = "verification.html#EVD-027", type = "evidence", status = "verified" },
  ["EVD-028"] = { title = "Runtime corruption machine evidence", href = "verification.html#EVD-028", type = "evidence", status = "verified" },
  ["EVD-029"] = { title = "Concurrent provisioning machine evidence", href = "verification.html#EVD-029", type = "evidence", status = "verified" },
  ["EVD-030"] = { title = "Spaces-path machine evidence", href = "verification.html#EVD-030", type = "evidence", status = "verified" },
  ["EVD-031"] = { title = "Quarto floor declaration machine evidence", href = "verification.html#EVD-031", type = "evidence", status = "verified" },
  ["EVD-032"] = { title = "Installed version diagnostics", href = "verification.html#EVD-032", type = "evidence", status = "verified" },
  ["EVD-033"] = { title = "Vacuous gate regression evidence", href = "verification.html#EVD-033", type = "evidence", status = "verified" },
  ["EVD-034"] = { title = "Perturbation harness evidence", href = "verification.html#EVD-034", type = "evidence", status = "verified" },
  ["EVD-035"] = { title = "Surface non-divergence evidence", href = "verification.html#EVD-035", type = "evidence", status = "verified" },
  ["EXT-GITHUB"] = { title = "GitHub", href = "architecture.html#EXT-GITHUB", type = "external-system", status = "approved" },
  ["EXT-OSLC"] = { title = "OSLC-compliant requirements management tool", href = "architecture.html#EXT-OSLC", type = "external-system", status = "approved" },
  ["FUN-001"] = { title = "Parse engineering declarations from Quarto source", href = "requirements.html#FUN-001", type = "functional-requirement", status = "approved" },
  ["FUN-002"] = { title = "Resolve authored relations through a canonical relation catalog", href = "requirements.html#FUN-002", type = "functional-requirement", status = "approved" },
  ["FUN-003"] = { title = "Materialize named queries as reusable graph views", href = "requirements.html#FUN-003", type = "functional-requirement", status = "approved" },
  ["FUN-004"] = { title = "Explore traceability interactively using semantic graph controls", href = "requirements.html#FUN-004", type = "functional-requirement", status = "approved" },
  ["FUN-005"] = { title = "Compare engineering states through baseline, diff, and impact analysis", href = "requirements.html#FUN-005", type = "functional-requirement", status = "approved" },
  ["FUN-006"] = { title = "Validate semantic parity of localized sources", href = "requirements.html#FUN-006", type = "functional-requirement", status = "approved" },
  ["FUN-007"] = { title = "Synchronize canonical extension assets into rendered examples", href = "requirements.html#FUN-007", type = "functional-requirement", status = "approved" },
  ["FUN-008"] = { title = "Publish safe declaration provenance for graph inspection", href = "requirements.html#FUN-008", type = "functional-requirement", status = "approved" },
  ["FUN-009"] = { title = "Collapse the page margin TOC without obscuring navigation", href = "requirements.html#FUN-009", type = "functional-requirement", status = "approved" },
  ["FUN-010"] = { title = "Discover OSLC RM services and advertised Resource Shapes", href = "interoperability.html#FUN-010", type = "functional-requirement", status = "approved" },
  ["FUN-011"] = { title = "Reconcile external requirements only through explicit identity bindings", href = "interoperability.html#FUN-011", type = "functional-requirement", status = "approved" },
  ["FUN-012"] = { title = "Execute an explicitly selected OSLC Query Capability without crawling members", href = "interoperability.html#FUN-012", type = "functional-requirement", status = "approved" },
  ["FUN-013"] = { title = "Materialize selected OSLC query members as independently provenance-bearing observations", href = "interoperability.html#FUN-013", type = "functional-requirement", status = "approved" },
  ["FUN-014"] = { title = "Normalize fetched GitHub issues without creating canonical identity", href = "interoperability.html#FUN-014", type = "functional-requirement", status = "approved" },
  ["FUN-015"] = { title = "Fetch GitHub issues through a bounded, cached, conditional transport", href = "interoperability.html#FUN-015", type = "functional-requirement", status = "approved" },
  ["FUN-016"] = { title = "Discover and traverse issue-list pages within explicit budgets", href = "interoperability.html#FUN-016", type = "functional-requirement", status = "approved" },
  ["FUN-017"] = { title = "Reconcile GitHub observations through the shared explicit-binding contracts", href = "interoperability.html#FUN-017", type = "functional-requirement", status = "approved" },
  ["FUN-018"] = { title = "Invoke an exact managed engine automatically during rendering", href = "requirements.html#FUN-018", type = "functional-requirement", status = "approved" },
  ["FUN-019"] = { title = "Render without a globally installed engine", href = "requirements.html#FUN-019", type = "functional-requirement", status = "approved" },
  ["FUN-020"] = { title = "Report the installed engine version independently of a project", href = "requirements.html#FUN-020", type = "functional-requirement", status = "approved" },
  ["FUN-021"] = { title = "Reject unmeasured quality assurance", href = "requirements.html#FUN-021", type = "functional-requirement", status = "approved" },
  ["FUN-022"] = { title = "Declare a stability tier for every published surface item", href = "requirements.html#FUN-022", type = "functional-requirement", status = "approved" },
  ["IF-001"] = { title = "QMD engineering declaration interface", href = "architecture.html#IF-001", type = "interface", status = "implemented" },
  ["IF-002"] = { title = "Canonical engineering snapshot", href = "architecture.html#IF-002", type = "interface", status = "implemented" },
  ["IF-003"] = { title = "Public graph projection contract", href = "architecture.html#IF-003", type = "interface", status = "implemented" },
  ["IF-004"] = { title = "CLI automation interface", href = "architecture.html#IF-004", type = "interface", status = "implemented" },
  ["IF-005"] = { title = "Read-only OSLC federation interface", href = "interoperability.html#IF-005", type = "interface", status = "implemented" },
  ["IF-006"] = { title = "Read-only GitHub issues adapter interface", href = "interoperability.html#IF-006", type = "interface", status = "implemented" },
  ["NFR-001"] = { title = "Produce deterministic engineering outputs", href = "requirements.html#NFR-001", type = "non-functional-requirement", status = "approved" },
  ["NFR-002"] = { title = "Keep public projections deny-by-default", href = "requirements.html#NFR-002", type = "non-functional-requirement", status = "approved" },
  ["NFR-003"] = { title = "Preserve a static equivalent for interactive views", href = "requirements.html#NFR-003", type = "non-functional-requirement", status = "approved" },
  ["NFR-004"] = { title = "Bound graph publication by explicit budgets", href = "requirements.html#NFR-004", type = "non-functional-requirement", status = "approved" },
  ["NFR-005"] = { title = "Resolve engineering semantics in the core only", href = "requirements.html#NFR-005", type = "non-functional-requirement", status = "approved" },
  ["NFR-006"] = { title = "Keep federation bounded, provenance-preserving, and fail-explicit", href = "interoperability.html#NFR-006", type = "non-functional-requirement", status = "approved" },
  ["NFR-007"] = { title = "Keep GitHub federation bounded, provenance-preserving, and rate-limit-explicit", href = "interoperability.html#NFR-007", type = "non-functional-requirement", status = "approved" },
  ["NFR-008"] = { title = "Keep provisioning project-local, atomic, and concurrency-safe", href = "requirements.html#NFR-008", type = "non-functional-requirement", status = "approved" },
  ["NFR-009"] = { title = "Support offline rendering from a valid cached runtime", href = "requirements.html#NFR-009", type = "non-functional-requirement", status = "approved" },
  ["NFR-010"] = { title = "Verify determinism under environment perturbation", href = "requirements.html#NFR-010", type = "non-functional-requirement", status = "approved" },
  ["RISK-001"] = { title = "Semantic meaning diverges across core and presentation layers", href = "architecture.html#RISK-001", type = "risk", status = "approved" },
  ["RISK-002"] = { title = "Public documentation leaks internal source information", href = "architecture.html#RISK-002", type = "risk", status = "approved" },
  ["RISK-003"] = { title = "Large graph projections overwhelm interactive documentation", href = "architecture.html#RISK-003", type = "risk", status = "approved" },
  ["RISK-004"] = { title = "Translations create a competing engineering model", href = "architecture.html#RISK-004", type = "risk", status = "approved" },
  ["RISK-005"] = { title = "External federation leaks credentials or silently trusts stale, changed, misidentified, or unbounded remote data", href = "interoperability.html#RISK-005", type = "risk", status = "approved" },
  ["RISK-012"] = { title = "Unbounded pagination, silent truncation, or rate-limit blindness makes external state look canonical", href = "interoperability.html#RISK-012", type = "risk", status = "approved" },
  ["RISK-013"] = { title = "First-use provisioning depends on Python, pip, and package availability", href = "architecture.html#RISK-013", type = "risk", status = "approved" },
  ["SRC-ANALYSIS"] = { title = "Canonical analysis module", href = "implementation.html#SRC-ANALYSIS", type = "source-module", status = "implemented" },
  ["SRC-BASELINE"] = { title = "Baseline module", href = "implementation.html#SRC-BASELINE", type = "source-module", status = "implemented" },
  ["SRC-BOOTSTRAP"] = { title = "Managed-runtime bootstrap", href = "implementation.html#SRC-BOOTSTRAP", type = "source-module", status = "implemented" },
  ["SRC-DIFF"] = { title = "Engineering diff module", href = "implementation.html#SRC-DIFF", type = "source-module", status = "implemented" },
  ["SRC-GITHUB-HTTP"] = { title = "GitHub bounded HTTP transport module", href = "interoperability.html#SRC-GITHUB-HTTP", type = "source-module", status = "implemented" },
  ["SRC-GITHUB-ISSUES"] = { title = "GitHub issues projection and discovery module", href = "interoperability.html#SRC-GITHUB-ISSUES", type = "source-module", status = "implemented" },
  ["SRC-GRAPH-CONTEXT"] = { title = "Cytoscape semantic context module", href = "implementation.html#SRC-GRAPH-CONTEXT", type = "source-module", status = "implemented" },
  ["SRC-GRAPH-EXPLORE"] = { title = "Cytoscape exploration module", href = "implementation.html#SRC-GRAPH-EXPLORE", type = "source-module", status = "implemented" },
  ["SRC-GRAPH-OUTPUT"] = { title = "Public graph output module", href = "implementation.html#SRC-GRAPH-OUTPUT", type = "source-module", status = "implemented" },
  ["SRC-GRAPH-PROJECTION"] = { title = "Graph selection and projection module", href = "implementation.html#SRC-GRAPH-PROJECTION", type = "source-module", status = "implemented" },
  ["SRC-IMPACT"] = { title = "Impact traversal module", href = "implementation.html#SRC-IMPACT", type = "source-module", status = "implemented" },
  ["SRC-MARGIN-SIDEBAR"] = { title = "Margin TOC toggle module", href = "implementation.html#SRC-MARGIN-SIDEBAR", type = "source-module", status = "implemented" },
  ["SRC-OSLC-CACHE"] = { title = "OSLC persistent cache module", href = "interoperability.html#SRC-OSLC-CACHE", type = "source-module", status = "implemented" },
  ["SRC-OSLC-FEDERATION"] = { title = "OSLC federation orchestration module", href = "interoperability.html#SRC-OSLC-FEDERATION", type = "source-module", status = "implemented" },
  ["SRC-OSLC-HTTP"] = { title = "OSLC bounded HTTP transport module", href = "interoperability.html#SRC-OSLC-HTTP", type = "source-module", status = "implemented" },
  ["SRC-OSLC-IMPORT"] = { title = "OSLC reviewed import-plan module", href = "interoperability.html#SRC-OSLC-IMPORT", type = "source-module", status = "implemented" },
  ["SRC-OSLC-OBSERVE"] = { title = "OSLC member observation module", href = "interoperability.html#SRC-OSLC-OBSERVE", type = "source-module", status = "implemented" },
  ["SRC-OSLC-QUERY"] = { title = "OSLC bounded query module", href = "interoperability.html#SRC-OSLC-QUERY", type = "source-module", status = "implemented" },
  ["SRC-OSLC-RDF"] = { title = "OSLC RDF normalization module", href = "interoperability.html#SRC-OSLC-RDF", type = "source-module", status = "implemented" },
  ["SRC-OSLC-RECONCILE"] = { title = "OSLC reconciliation module", href = "interoperability.html#SRC-OSLC-RECONCILE", type = "source-module", status = "implemented" },
  ["SRC-OSLC-RM"] = { title = "OSLC RM semantic projection module", href = "interoperability.html#SRC-OSLC-RM", type = "source-module", status = "implemented" },
  ["SRC-PARSER"] = { title = "QMD declaration parser module", href = "implementation.html#SRC-PARSER", type = "source-module", status = "implemented" },
  ["SRC-PRE-RENDER"] = { title = "Canonical pre-render integration module", href = "implementation.html#SRC-PRE-RENDER", type = "source-module", status = "implemented" },
  ["SRC-QUALITY"] = { title = "Quality-gate module", href = "implementation.html#SRC-QUALITY", type = "source-module", status = "implemented" },
  ["SRC-QUARTO-INTEGRATION"] = { title = "Canonical Quarto pre-render application service", href = "implementation.html#SRC-QUARTO-INTEGRATION", type = "source-module", status = "implemented" },
  ["SRC-QUERIES"] = { title = "Named-query module", href = "implementation.html#SRC-QUERIES", type = "source-module", status = "implemented" },
  ["SRC-RELATIONS"] = { title = "Canonical relation catalog module", href = "implementation.html#SRC-RELATIONS", type = "source-module", status = "implemented" },
  ["SRC-RULES"] = { title = "Governance rule module", href = "implementation.html#SRC-RULES", type = "source-module", status = "implemented" },
  ["STK-001"] = { title = "Engineering teams need lifecycle-wide traceability", href = "drivers.html#STK-001", type = "stakeholder-need", status = "approved" },
  ["STK-002"] = { title = "Engineers need the engineering model to remain readable documentation", href = "drivers.html#STK-002", type = "stakeholder-need", status = "approved" },
  ["STK-003"] = { title = "Teams need reproducible governance in Git and CI", href = "drivers.html#STK-003", type = "stakeholder-need", status = "approved" },
  ["STK-004"] = { title = "Architecture choices need durable rationale and traceability", href = "drivers.html#STK-004", type = "stakeholder-need", status = "approved" },
  ["STK-005"] = { title = "Multilingual teams need one engineering graph", href = "drivers.html#STK-005", type = "stakeholder-need", status = "approved" },
  ["STK-006"] = { title = "Engineering teams need standards-based federation without semantic drift", href = "interoperability.html#STK-006", type = "stakeholder-need", status = "approved" },
  ["STK-007"] = { title = "Engineering teams need requirements linked to live issue-tracker state without importing the tracker", href = "interoperability.html#STK-007", type = "stakeholder-need", status = "approved" },
  ["STK-008"] = { title = "Quarto authors need the extension to be the whole installation", href = "drivers.html#STK-008", type = "stakeholder-need", status = "approved" },
  ["SYS-001"] = { title = "Maintain a canonical typed engineering graph", href = "drivers.html#SYS-001", type = "system-requirement", status = "approved" },
  ["SYS-002"] = { title = "Use Quarto as the executable documentation interface", href = "drivers.html#SYS-002", type = "system-requirement", status = "approved" },
  ["SYS-003"] = { title = "Provide deterministic validation and quality gates", href = "drivers.html#SYS-003", type = "system-requirement", status = "approved" },
  ["SYS-004"] = { title = "Treat architecture decisions as first-class engineering objects", href = "drivers.html#SYS-004", type = "system-requirement", status = "approved" },
  ["SYS-005"] = { title = "Localize presentation without duplicating engineering semantics", href = "drivers.html#SYS-005", type = "system-requirement", status = "approved" },
  ["SYS-006"] = { title = "Publish bounded semantic graph projections for exploration", href = "drivers.html#SYS-006", type = "system-requirement", status = "approved" },
  ["SYS-007"] = { title = "Federate OSLC requirements through a bounded read-only adapter", href = "interoperability.html#SYS-007", type = "system-requirement", status = "approved" },
  ["SYS-008"] = { title = "Federate GitHub issues as read-only, provenance-bound observations", href = "interoperability.html#SYS-008", type = "system-requirement", status = "approved" },
  ["SYS-009"] = { title = "Deliver the semantic engine through the activated extension itself", href = "drivers.html#SYS-009", type = "system-requirement", status = "approved" },
  ["SYS-QUARTO-NEEDS"] = { title = "Quarto-Needs", href = "architecture.html#SYS-QUARTO-NEEDS", type = "system", status = "approved" },
  ["TC-001"] = { title = "Canonical graph and snapshot regression", href = "verification.html#TC-001", type = "test-case", status = "passed" },
  ["TC-002"] = { title = "Quarto progressive-render regression", href = "verification.html#TC-002", type = "test-case", status = "passed" },
  ["TC-003"] = { title = "Strict governance regression", href = "verification.html#TC-003", type = "test-case", status = "passed" },
  ["TC-004"] = { title = "Architecture-decision governance regression", href = "verification.html#TC-004", type = "test-case", status = "passed" },
  ["TC-005"] = { title = "Localized-source semantic-parity regression", href = "verification.html#TC-005", type = "test-case", status = "passed" },
  ["TC-006"] = { title = "Public graph contract and safety regression", href = "verification.html#TC-006", type = "test-case", status = "passed" },
  ["TC-007"] = { title = "QMD declaration parsing regression", href = "verification.html#TC-007", type = "test-case", status = "passed" },
  ["TC-008"] = { title = "Relation-catalog semantic regression", href = "verification.html#TC-008", type = "test-case", status = "passed" },
  ["TC-009"] = { title = "Named-query graph-view regression", href = "verification.html#TC-009", type = "test-case", status = "passed" },
  ["TC-010"] = { title = "Interactive graph exploration asset regression", href = "verification.html#TC-010", type = "test-case", status = "passed" },
  ["TC-011"] = { title = "Baseline, diff, and impact regression", href = "verification.html#TC-011", type = "test-case", status = "passed" },
  ["TC-012"] = { title = "Canonical extension synchronization regression", href = "verification.html#TC-012", type = "test-case", status = "passed" },
  ["TC-013"] = { title = "Deterministic output regression", href = "verification.html#TC-013", type = "test-case", status = "passed" },
  ["TC-014"] = { title = "Margin TOC toggle positioning regression", href = "verification.html#TC-014", type = "test-case", status = "passed" },
  ["TC-015"] = { title = "OSLC federation orchestration regression", href = "interoperability.html#TC-015", type = "test-case", status = "passed" },
  ["TC-016"] = { title = "OSLC explicit-identity reconciliation regression", href = "interoperability.html#TC-016", type = "test-case", status = "passed" },
  ["TC-017"] = { title = "OSLC bounded query execution regression", href = "interoperability.html#TC-017", type = "test-case", status = "passed" },
  ["TC-018"] = { title = "OSLC member observation provenance regression", href = "interoperability.html#TC-018", type = "test-case", status = "passed" },
  ["TC-019"] = { title = "OSLC reviewed import-plan directive regression", href = "interoperability.html#TC-019", type = "test-case", status = "passed" },
  ["TC-020"] = { title = "GitHub issue fetch-and-normalize regression", href = "interoperability.html#TC-020", type = "test-case", status = "passed" },
  ["TC-021"] = { title = "GitHub conditional-request cache regression", href = "interoperability.html#TC-021", type = "test-case", status = "passed" },
  ["TC-022"] = { title = "GitHub bounded pagination regression", href = "interoperability.html#TC-022", type = "test-case", status = "passed" },
  ["TC-023"] = { title = "GitHub explicit-binding reconciliation regression", href = "interoperability.html#TC-023", type = "test-case", status = "passed" },
  ["TC-024"] = { title = "GitHub rate-limit classification regression", href = "interoperability.html#TC-024", type = "test-case", status = "passed" },
  ["TC-025"] = { title = "Extension-first clean render", href = "verification.html#TC-025", type = "test-case", status = "passed" },
  ["TC-026"] = { title = "Offline second render", href = "verification.html#TC-026", type = "test-case", status = "passed" },
  ["TC-027"] = { title = "Version skew isolation", href = "verification.html#TC-027", type = "test-case", status = "passed" },
  ["TC-028"] = { title = "Runtime corruption", href = "verification.html#TC-028", type = "test-case", status = "passed" },
  ["TC-029"] = { title = "Concurrent provisioning", href = "verification.html#TC-029", type = "test-case", status = "passed" },
  ["TC-030"] = { title = "Project path with spaces", href = "verification.html#TC-030", type = "test-case", status = "passed" },
  ["TC-031"] = { title = "Declared Quarto floor", href = "verification.html#TC-031", type = "test-case", status = "passed" },
  ["TC-032"] = { title = "Installed version diagnostics", href = "verification.html#TC-032", type = "test-case", status = "passed" },
  ["TC-033"] = { title = "Reject vacuous gate verdicts", href = "verification.html#TC-033", type = "test-case", status = "passed" },
  ["TC-034"] = { title = "Compare artifacts across perturbed subprocess runs", href = "verification.html#TC-034", type = "test-case", status = "passed" },
  ["TC-035"] = { title = "Compare the declared surface against the real parser and routing", href = "verification.html#TC-035", type = "test-case", status = "passed" },
}
