"""The canonical Quarto pre-render service, pinned by its artifacts.

Phase 8B gives the extension bootstrap a way to run the semantic build
without going through the CLI. The risk in that refactor is a second
semantic path: an engine invoked by the extension that writes subtly
different bytes from the one invoked by `quarto-needs scan`.

These tests make that impossible to do quietly. They characterize one
representative project -- requirements with findings, configured named
queries, and a C4 hierarchy -- across every artifact family `scan` writes,
and then assert the CLI path and the service path produce byte-identical
output and the same exit status.

Spec: docs/superpowers/specs/2026-09-02-extension-first-distribution-design.md (§7)
Plan: docs/superpowers/plans/2026-09-02-extension-first-distribution.md (Task 2)
"""
from __future__ import annotations

import ast
from pathlib import Path

from quarto_needs import cli

SOURCE = Path(__file__).resolve().parents[1] / "src" / "quarto_needs"

PROJECT_QMD = """---
title: "Pre-render service fixture"
---

::: {.need #REQ-1 type="functional-requirement" status="approved" priority="high"}
## Authenticate the user

The system shall authenticate the user.

### Rationale
Protect private data.
:::

::: {.need #REQ-2 type="functional-requirement" status="approved" priority="high" derives-from="REQ-1"}
## Authenticate with a password

The system shall accept a password.

### Rationale
Derived from the parent requirement.
:::

::: {.need #TC-1 type="test-case" status="passed" verifies="REQ-1"}
## Login test

Signs a user in.
:::

::: {.need #SYS-1 type="system" status="draft"}
## The system
:::

::: {.need #CONT-1 type="container" status="draft" part-of="SYS-1"}
## The container
:::

::: {.need #COMP-1 type="component" status="draft" part-of="CONT-1"}
## The component
:::

::: {.need #ACTOR-1 type="actor" status="draft" depends-on="SYS-1"}
## The actor
:::
"""

# Named queries drive the named graph projections, so one config exercises
# both the query surface and the per-view graph artifacts.
PROJECT_CONFIG = """[queries.deriving-requirements]
all = [
  { relation = "derives-from", direction = "out", op = "exists" },
]
sort = ["id:asc"]

[queries.approved-high-unverified]
all = [
  { field = "status", op = "eq", value = "approved" },
  { field = "priority", op = "in", values = ["high", "critical"] },
  { relation = "verified-by", direction = "out", op = "missing" },
]
"""


def representative_project(root: Path) -> Path:
    """One project exercising every artifact family `scan` writes."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "index.qmd").write_text(PROJECT_QMD, encoding="utf-8")
    (root / ".quarto-needs.toml").write_text(PROJECT_CONFIG, encoding="utf-8")
    return root


def artifacts(root: Path) -> dict[str, bytes]:
    """Every generated byte, keyed by path relative to the project."""
    generated: dict[str, bytes] = {}
    for directory in (root / ".quarto-needs", root / "_extensions"):
        if not directory.is_dir():
            continue
        for path in sorted(directory.rglob("*")):
            if path.is_file():
                generated[path.relative_to(root).as_posix()] = path.read_bytes()
    return generated


def test_scan_writes_every_expected_artifact_family(tmp_path) -> None:
    root = representative_project(tmp_path / "project")

    status = cli.build(root, quiet=True)

    assert status == 0
    written = artifacts(root)

    # The canonical graph, and the Lua lookup index the filter reads.
    assert ".quarto-needs/needs.json" in written
    assert "_extensions/quarto-needs/generated-index.lua" in written

    # The default graph view, its DOT sibling, and the view manifest.
    assert ".quarto-needs/graphs/need-graph-1.json" in written
    assert ".quarto-needs/graphs/need-graph-1.dot" in written
    assert ".quarto-needs/graphs/views.json" in written

    # One JSON+DOT projection per configured named query.
    for query in ("deriving-requirements", "approved-high-unverified"):
        assert f".quarto-needs/graphs/need-graph-query-{query}.json" in written
        assert f".quarto-needs/graphs/need-graph-query-{query}.dot" in written

    # C4 artifacts, which need no project configuration at all: one view per
    # system/container, the code-level table, and each renderer's source.
    assert ".quarto-needs/graphs/c4-context-SYS-1.json" in written
    assert ".quarto-needs/graphs/c4-container-SYS-1.json" in written
    assert ".quarto-needs/graphs/c4-component-CONT-1.json" in written
    assert ".quarto-needs/graphs/c4-code-COMP-1.json" in written
    for backend in ("d2", "plantuml", "structurizr"):
        assert f".quarto-needs/graphs/c4-context-SYS-1.{backend}.json" in written


def test_scan_is_byte_deterministic_across_runs(tmp_path) -> None:
    """A stable snapshot must produce stable artifacts.

    Without this, the parity assertion below could pass on noise.
    """
    first_root = representative_project(tmp_path / "first")
    second_root = representative_project(tmp_path / "second")

    assert cli.build(first_root, quiet=True) == 0
    assert cli.build(second_root, quiet=True) == 0

    assert artifacts(first_root) == artifacts(second_root)


def test_scan_reports_findings_without_failing_a_valid_project(tmp_path) -> None:
    """Exit status is part of the contract the bootstrap must reproduce."""
    from quarto_needs.analysis import analyze_project
    from quarto_needs.config import load_config

    root = representative_project(tmp_path / "project")
    result = analyze_project(root, config=load_config(root))

    assert result.snapshot is not None
    # Findings exist (nothing implements REQ-1/REQ-2), but none is an error,
    # so the build succeeds. Both halves matter.
    assert result.findings
    assert not [f for f in result.findings if f.severity == "error"]
    assert cli.build(root, quiet=True) == 0


def test_a_structurally_invalid_project_fails_the_build(tmp_path) -> None:
    root = tmp_path / "broken"
    root.mkdir()
    (root / "index.qmd").write_text(
        '::: {.need #REQ-1 type="functional-requirement" verified-by="NOPE-1"}\n'
        "## Dangling\n"
        ":::\n",
        encoding="utf-8",
    )

    assert cli.build(root, quiet=True) == 1


# --- The parity contract: one semantic path, two callers --------------------


def test_the_service_and_the_cli_write_identical_artifacts(tmp_path) -> None:
    """`scan` and the extension bootstrap must be the same operation.

    If these ever diverge, the extension has grown a second semantic path --
    exactly what the spec forbids.
    """
    from quarto_needs.quarto_integration import run_quarto_pre_render

    cli_root = representative_project(tmp_path / "via-cli")
    service_root = representative_project(tmp_path / "via-service")

    cli_status = cli.build(cli_root, quiet=True)
    service_status = run_quarto_pre_render(service_root, quiet=True)

    assert cli_status == service_status == 0
    assert artifacts(cli_root) == artifacts(service_root)


def test_the_service_reports_the_same_failure_status_as_the_cli(tmp_path) -> None:
    from quarto_needs.quarto_integration import run_quarto_pre_render

    def broken(root: Path) -> Path:
        root.mkdir(parents=True)
        (root / "index.qmd").write_text(
            '::: {.need #REQ-1 type="functional-requirement" verified-by="NOPE-1"}\n'
            "## Dangling\n"
            ":::\n",
            encoding="utf-8",
        )
        return root

    assert cli.build(broken(tmp_path / "a"), quiet=True) == run_quarto_pre_render(
        broken(tmp_path / "b"), quiet=True
    ) == 1


# --- Architectural boundary -------------------------------------------------


def test_the_integration_service_imports_no_presentation_code() -> None:
    """The service is a semantic entry point, not a renderer.

    Lua, JavaScript and browser assets are presentation; the pre-render
    service exists to produce the artifacts they later consume, so it must
    not reach back into them.
    """
    module = SOURCE / "quarto_integration.py"
    tree = ast.parse(module.read_text(encoding="utf-8"))

    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)
        elif isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)

    # The service writes `generated-index.lua`, so naming that path is
    # expected; depending on the CLI, the language server, or the console
    # presentation layer is not. Imports are the boundary that matters.
    forbidden = {
        "lsp_server",
        "console",
        "cli",
        "cli_entry",
        "cli_dispatch",
        "argparse",
    }
    assert not (imported & forbidden), imported & forbidden

    # Nor may it grow a command-line surface of its own: it is an
    # application service with one caller-supplied root.
    assert "argparse" not in module.read_text(encoding="utf-8")
