return {
  ["IAM-COMP-001"] = { title = "Serviço de autenticação", href = "architecture/components.html#IAM-COMP-001", type = "component", status = "implemented" },
  ["IAM-COMP-002"] = { title = "Motor de políticas", href = "architecture/components.html#IAM-COMP-002", type = "component", status = "implemented" },
  ["IAM-COMP-003"] = { title = "Orquestrador de ciclo de vida", href = "architecture/components.html#IAM-COMP-003", type = "component", status = "implemented" },
  ["IAM-COMP-004"] = { title = "Cofre de auditoria", href = "architecture/components.html#IAM-COMP-004", type = "component", status = "implemented" },
  ["IAM-COMP-005"] = { title = "Serviço de recuperação", href = "architecture/components.html#IAM-COMP-005", type = "component", status = "implemented" },
  ["IAM-COMP-006"] = { title = "Portal de identidade", href = "architecture/components.html#IAM-COMP-006", type = "component", status = "implemented" },
  ["IAM-EVD-001"] = { title = "Relatório de autenticação 2026-08-25", href = "verification/evidence.html#IAM-EVD-001", type = "evidence", status = "verified" },
  ["IAM-EVD-002"] = { title = "Relatório de MFA administrativo", href = "verification/evidence.html#IAM-EVD-002", type = "evidence", status = "verified" },
  ["IAM-EVD-003"] = { title = "Relatório de revogação de sessão", href = "verification/evidence.html#IAM-EVD-003", type = "evidence", status = "verified" },
  ["IAM-EVD-004"] = { title = "Relatório de política por atributo", href = "verification/evidence.html#IAM-EVD-004", type = "evidence", status = "verified" },
  ["IAM-EVD-005"] = { title = "Relatório de negação padrão", href = "verification/evidence.html#IAM-EVD-005", type = "evidence", status = "verified" },
  ["IAM-EVD-006"] = { title = "Relatório de carga da autorização", href = "verification/evidence.html#IAM-EVD-006", type = "evidence", status = "verified" },
  ["IAM-EVD-007"] = { title = "Relatório de provisão por admissão", href = "verification/evidence.html#IAM-EVD-007", type = "evidence", status = "verified" },
  ["IAM-EVD-008"] = { title = "Relatório de suspensão por desligamento", href = "verification/evidence.html#IAM-EVD-008", type = "evidence", status = "verified" },
  ["IAM-EVD-009"] = { title = "Relatório de campanha de revisão", href = "verification/evidence.html#IAM-EVD-009", type = "evidence", status = "verified" },
  ["IAM-EVD-010"] = { title = "Relatório de evento de autorização", href = "verification/evidence.html#IAM-EVD-010", type = "evidence", status = "verified" },
  ["IAM-EVD-011"] = { title = "Relatório de consulta e retenção", href = "verification/evidence.html#IAM-EVD-011", type = "evidence", status = "verified" },
  ["IAM-EVD-012"] = { title = "Relatório de recuperação reforçada", href = "verification/evidence.html#IAM-EVD-012", type = "evidence", status = "verified" },
  ["IAM-EVD-013"] = { title = "Relatório de acessibilidade do portal", href = "verification/evidence.html#IAM-EVD-013", type = "evidence", status = "verified" },
  ["IAM-EVD-014"] = { title = "Relatório de disponibilidade da autenticação", href = "verification/evidence.html#IAM-EVD-014", type = "evidence", status = "verified" },
  ["IAM-EVD-015"] = { title = "Relatório de minimização de dados", href = "verification/evidence.html#IAM-EVD-015", type = "evidence", status = "verified" },
  ["IAM-EVD-016"] = { title = "Relatório de criptografia de credenciais", href = "verification/evidence.html#IAM-EVD-016", type = "evidence", status = "verified" },
  ["IAM-EVD-017"] = { title = "Relatório de interoperabilidade OIDC", href = "verification/evidence.html#IAM-EVD-017", type = "evidence", status = "verified" },
  ["IAM-FUN-001"] = { title = "Validar credenciais corporativas", href = "requirements/functional.html#IAM-FUN-001", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-002"] = { title = "Exigir MFA para acesso privilegiado", href = "requirements/functional.html#IAM-FUN-002", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-003"] = { title = "Revogar sessões após mudança de risco", href = "requirements/functional.html#IAM-FUN-003", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-004"] = { title = "Avaliar políticas por atributo", href = "requirements/functional.html#IAM-FUN-004", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-005"] = { title = "Aplicar menor privilégio por padrão", href = "requirements/functional.html#IAM-FUN-005", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-006"] = { title = "Registrar delegação temporária", href = "requirements/functional.html#IAM-FUN-006", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-007"] = { title = "Provisionar conta por evento de admissão", href = "requirements/functional.html#IAM-FUN-007", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-008"] = { title = "Suspender conta no desligamento", href = "requirements/functional.html#IAM-FUN-008", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-009"] = { title = "Solicitar revisão periódica de acesso", href = "requirements/functional.html#IAM-FUN-009", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-010"] = { title = "Registrar decisão de autorização", href = "requirements/functional.html#IAM-FUN-010", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-011"] = { title = "Consultar trilha de auditoria por conta", href = "requirements/functional.html#IAM-FUN-011", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-012"] = { title = "Recuperar conta com verificação reforçada", href = "requirements/functional.html#IAM-FUN-012", type = "functional-requirement", status = "approved" },
  ["IAM-FUN-013"] = { title = "Delegar recuperação ao suporte supervisionado", href = "requirements/functional.html#IAM-FUN-013", type = "functional-requirement", status = "in-review" },
  ["IAM-FUN-014"] = { title = "Provisionar grupos via SCIM", href = "requirements/functional.html#IAM-FUN-014", type = "functional-requirement", status = "draft" },
  ["IAM-FUN-015"] = { title = "Permitir senha compartilhada por equipe", href = "requirements/functional.html#IAM-FUN-015", type = "functional-requirement", status = "disapproved" },
  ["IAM-IF-001"] = { title = "API OpenID Connect", href = "architecture/components.html#IAM-IF-001", type = "interface", status = "implemented" },
  ["IAM-IF-002"] = { title = "API SCIM de provisão", href = "architecture/components.html#IAM-IF-002", type = "interface", status = "implemented" },
  ["IAM-IF-003"] = { title = "Fluxo de eventos de auditoria", href = "architecture/components.html#IAM-IF-003", type = "interface", status = "implemented" },
  ["IAM-NFR-001"] = { title = "Proteger credenciais em trânsito e repouso", href = "requirements/non-functional.html#IAM-NFR-001", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-002"] = { title = "Manter autenticação disponível", href = "requirements/non-functional.html#IAM-NFR-002", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-003"] = { title = "Minimizar dados pessoais em eventos", href = "requirements/non-functional.html#IAM-NFR-003", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-004"] = { title = "Responder decisão de acesso em até 200 ms", href = "requirements/non-functional.html#IAM-NFR-004", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-005"] = { title = "Preservar integridade de auditoria", href = "requirements/non-functional.html#IAM-NFR-005", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-006"] = { title = "Oferecer autenticação acessível", href = "requirements/non-functional.html#IAM-NFR-006", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-007"] = { title = "Reter evidências pelo prazo regulatório", href = "requirements/non-functional.html#IAM-NFR-007", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-008"] = { title = "Restaurar fluxo de recuperação em até quatro horas", href = "requirements/non-functional.html#IAM-NFR-008", type = "non-functional-requirement", status = "approved" },
  ["IAM-NFR-009"] = { title = "Expor métricas operacionais de identidade", href = "requirements/non-functional.html#IAM-NFR-009", type = "non-functional-requirement", status = "in-review" },
  ["IAM-NFR-010"] = { title = "Medir consumo energético por autenticação", href = "requirements/non-functional.html#IAM-NFR-010", type = "non-functional-requirement", status = "draft" },
  ["IAM-RISK-001"] = { title = "Tomada de conta por phishing", href = "risks/security.html#IAM-RISK-001", type = "risk", status = "in-review" },
  ["IAM-RISK-002"] = { title = "Escalada de privilégio por política permissiva", href = "risks/security.html#IAM-RISK-002", type = "risk", status = "approved" },
  ["IAM-RISK-003"] = { title = "Vazamento de dados pessoais em logs", href = "risks/security.html#IAM-RISK-003", type = "risk", status = "approved" },
  ["IAM-RISK-004"] = { title = "Indisponibilidade durante recuperação de conta", href = "risks/security.html#IAM-RISK-004", type = "risk", status = "draft" },
  ["IAM-STK-001"] = { title = "Diretora de segurança precisa reduzir invasões de conta", href = "context/stakeholders.html#IAM-STK-001", type = "stakeholder-need", status = "approved" },
  ["IAM-STK-002"] = { title = "Encarregado de dados precisa controlar exposição de dados pessoais", href = "context/stakeholders.html#IAM-STK-002", type = "stakeholder-need", status = "approved" },
  ["IAM-STK-003"] = { title = "Operações precisam recuperar acesso com segurança", href = "context/stakeholders.html#IAM-STK-003", type = "stakeholder-need", status = "approved" },
  ["IAM-STK-004"] = { title = "Equipes de produto precisam integrar aplicações rapidamente", href = "context/stakeholders.html#IAM-STK-004", type = "stakeholder-need", status = "approved" },
  ["IAM-STK-005"] = { title = "Auditoria precisa de rastreabilidade de decisões de acesso", href = "context/stakeholders.html#IAM-STK-005", type = "stakeholder-need", status = "approved" },
  ["IAM-SYS-001"] = { title = "Autenticar identidades antes de emitir sessão", href = "requirements/system.html#IAM-SYS-001", type = "system-requirement", status = "approved" },
  ["IAM-SYS-002"] = { title = "Decidir acesso por política central", href = "requirements/system.html#IAM-SYS-002", type = "system-requirement", status = "approved" },
  ["IAM-SYS-003"] = { title = "Gerir o ciclo de vida de contas", href = "requirements/system.html#IAM-SYS-003", type = "system-requirement", status = "approved" },
  ["IAM-SYS-004"] = { title = "Registrar eventos de identidade imutáveis", href = "requirements/system.html#IAM-SYS-004", type = "system-requirement", status = "approved" },
  ["IAM-SYS-005"] = { title = "Recuperar acesso com prova de identidade", href = "requirements/system.html#IAM-SYS-005", type = "system-requirement", status = "approved" },
  ["IAM-SYS-006"] = { title = "Expor integração de identidade padronizada", href = "requirements/system.html#IAM-SYS-006", type = "system-requirement", status = "approved" },
  ["IAM-SYS-007"] = { title = "Detectar anomalias de privilégio", href = "requirements/system.html#IAM-SYS-007", type = "system-requirement", status = "in-review" },
  ["IAM-SYS-008"] = { title = "Oferecer credencial móvel corporativa", href = "requirements/system.html#IAM-SYS-008", type = "system-requirement", status = "draft" },
  ["IAM-TC-001"] = { title = "Autenticação com credencial válida", href = "verification/test-cases.html#IAM-TC-001", type = "test-case", status = "passed" },
  ["IAM-TC-002"] = { title = "MFA obrigatório para administrador", href = "verification/test-cases.html#IAM-TC-002", type = "test-case", status = "passed" },
  ["IAM-TC-003"] = { title = "Revogação de sessão suspensa", href = "verification/test-cases.html#IAM-TC-003", type = "test-case", status = "passed" },
  ["IAM-TC-004"] = { title = "Decisão por atributo", href = "verification/test-cases.html#IAM-TC-004", type = "test-case", status = "passed" },
  ["IAM-TC-005"] = { title = "Negação sem regra permissiva", href = "verification/test-cases.html#IAM-TC-005", type = "test-case", status = "passed" },
  ["IAM-TC-006"] = { title = "Latência da decisão de acesso", href = "verification/test-cases.html#IAM-TC-006", type = "test-case", status = "passed" },
  ["IAM-TC-007"] = { title = "Criação por evento de admissão", href = "verification/test-cases.html#IAM-TC-007", type = "test-case", status = "passed" },
  ["IAM-TC-008"] = { title = "Suspensão por desligamento", href = "verification/test-cases.html#IAM-TC-008", type = "test-case", status = "passed" },
  ["IAM-TC-009"] = { title = "Campanha de revisão de acesso", href = "verification/test-cases.html#IAM-TC-009", type = "test-case", status = "passed" },
  ["IAM-TC-010"] = { title = "Registro de decisão de autorização", href = "verification/test-cases.html#IAM-TC-010", type = "test-case", status = "passed" },
  ["IAM-TC-011"] = { title = "Consulta e retenção de trilha", href = "verification/test-cases.html#IAM-TC-011", type = "test-case", status = "passed" },
  ["IAM-TC-012"] = { title = "Recuperação reforçada", href = "verification/test-cases.html#IAM-TC-012", type = "test-case", status = "passed" },
  ["IAM-TC-013"] = { title = "Acessibilidade da autenticação", href = "verification/test-cases.html#IAM-TC-013", type = "test-case", status = "passed" },
  ["IAM-TC-014"] = { title = "Disponibilidade de autenticação", href = "verification/test-cases.html#IAM-TC-014", type = "test-case", status = "passed" },
  ["IAM-TC-015"] = { title = "Minimização de evento pessoal", href = "verification/test-cases.html#IAM-TC-015", type = "test-case", status = "passed" },
  ["IAM-TC-016"] = { title = "Criptografia de credenciais e segredos", href = "verification/test-cases.html#IAM-TC-016", type = "test-case", status = "passed" },
  ["IAM-TC-017"] = { title = "Federação OpenID Connect", href = "verification/test-cases.html#IAM-TC-017", type = "test-case", status = "passed" },
}
